import type { Metadata } from "next";
import { VT323, Inter } from "next/font/google";
import "./globals.css";

const vt323 = VT323({ 
  weight: "400", 
  subsets: ["latin"], 
  variable: "--font-vt323" 
});

const inter = Inter({ 
  subsets: ["latin"], 
  variable: "--font-inter"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={`${vt323.variable} ${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
